### ISSUE TITLE
NoMethodError: undefined method `attr_accessible' for MongoidShortener::ShortenedUrl:Class

### ISSUE THREAD

**Issue by parasharrk** [siong1987/mongoid_shortener#3]
$ rails c
Loading development environment (Rails 4.1.8)
2.1.2 :001 > MongoidShortener.generate("http://google.com")
NoMethodError: undefined method `attr_accessible' for MongoidShortener::ShortenedUrl:Class
  from /home/work/osp/mongoid_shortener/app/models/mongoid_shortener/shortened_url.rb:26:in `<class:ShortenedUrl>'
  from /home/work/osp/mongoid_shortener/app/models/mongoid_shortener/shortened_url.rb:2:in `<module:MongoidShortener>'
  from /home/work/osp/mongoid_shortener/app/models/mongoid_shortener/shortened_url.rb:1:in `<top (required)>'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:443:in `load'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:443:in `block in load_file'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:633:in `new_constants_in'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:442:in `load_file'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:342:in `require_or_load'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:480:in `load_missing_constant'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:180:in `const_missing'
  from /home/work/osp/mongoid_shortener/lib/mongoid_shortener.rb:10:in `generate'
  from (irb):1
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/railties-4.1.8/lib/rails/commands/console.rb:90:in `start'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/railties-4.1.8/lib/rails/commands/console.rb:9:in `start'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:69:in `console'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
  from /home/work/sntq/say_no_to_q/bin/rails:8:in `<top (required)>'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `block in load'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
  from /home/.rvm/gems/ruby-2.1.2@say_no_to_q/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
  from /home/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'

**Comment by parasharrk** [comment]
this issue is fixed with https://github.com/siong1987/mongoid_shortener/pull/5, so closing this issue.
